module Top #(
    parameter DATA_WIDTH = 8,   // Data width of each FIFO entry
    parameter FIFO_DEPTH = 16   // Buffer size
)       (
         // Write Domain Interface
         input wclk,                   // Write clock domain
         input wrst,                   // Write domain active-high reset
         input w_en,                   // Write enable request
         input [DATA_WIDTH-1:0] din,   // Input data bus
         output wfull,                 // Write full status flag
           
         // Read Domain Interface
         input rclk,                   // Read clock domain
         input rrst,                   // Read domain active-high reset
         input r_en,                   // Read enable request
         output [DATA_WIDTH-1:0] dout, // Output data bus
         output rempty                 // Read empty status flag
         );                

    // Local parameter calculation
    localparam ADDR = $clog2(FIFO_DEPTH);

    wire [ADDR:0] wptr, rptr;           // Gray-coded pointers generated by controllers
    wire [ADDR:0] wq2_rptr, rq2_wptr;   // Synchronized gray-coded pointers
    wire [ADDR-1:0] waddr, raddr;       // Memory addressing lines

    // Dual-Port Memory Core
    // Handles independent write and read clock domains for data storage.
    // Write is gated to prevent writing when the FIFO is full.
    mem #(
        .DATA_WIDTH(DATA_WIDTH),
        .FIFO_DEPTH(FIFO_DEPTH)
    ) memory_core(
        .wclk(wclk),
        .wclken(w_en & !wfull), // Gate write clock enable with the full flag guard
        .waddr(waddr),
        .din(din),
        .rclk(rclk),
        .rclken(r_en & !rempty),
        .raddr(raddr),
        .dout(dout)
    );

    // Read-to-Write Domain Synchronizer
    // Synchronizes the gray-coded read pointer into the write clock domain
    synchronizer #(
        .FIFO_DEPTH(FIFO_DEPTH)
    ) rsynch(
        .clk(wclk),
        .rst(wrst),
        .ptr_in(rptr),
        .ptr_out(wq2_rptr)
    );

    // Write-to-Read Domain Synchronizer
    // Synchronizes the gray-coded write pointer into the read clock domain
    synchronizer #(
        .FIFO_DEPTH(FIFO_DEPTH)
    ) wsynch(
        .clk(rclk),
        .rst(rrst),
        .ptr_in(wptr),
        .ptr_out(rq2_wptr)
    );

    // Write Domain Controller
    // Manages write address generation, binary-to-gray pointer conversion, and full flag generation using the synchronized read pointer.
    w_ctrl #(
        .FIFO_DEPTH(FIFO_DEPTH)
    ) write(
        .wclk(wclk),
        .wrst(wrst),
        .w_en(w_en),
        .wq2_rptr(wq2_rptr),
        .wfull(wfull),
        .waddr(waddr),
        .wptr(wptr)
    );

    // Read Domain Controller
    // Manages read address generation, binary-to-gray pointer conversion, and empty flag generation using the synchronized write pointer.
    r_ctrl #(
        .FIFO_DEPTH(FIFO_DEPTH)
    ) read(
        .rclk(rclk),
        .rrst(rrst),
        .r_en(r_en),
        .rq2_wptr(rq2_wptr),
        .rempty(rempty),
        .raddr(raddr),
        .rptr(rptr)
    );

endmodule